### ISSUE TITLE
Issues related to viewing output

### ISSUE THREAD

**Issue by BlackCanyon** [openai/universe-starter-agent#102]
This is the output I get when I run the command:

> Executing the following commands:
> mkdir -p /tmp/pong
> echo /anaconda/envs/StarterAgent/bin/python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong --visualise > /tmp/pong/cmd.sh
> kill $( lsof -i:12345 -t ) > /dev/null 2>&1
> kill $( lsof -i:12222-12224 -t ) > /dev/null 2>&1
> tmux kill-session -t a3c
> tmux new-session -s a3c -n ps -d bash
> tmux new-window -t a3c -n w-0 bash
> tmux new-window -t a3c -n w-1 bash
> tmux new-window -t a3c -n tb bash
> tmux new-window -t a3c -n htop bash
> sleep 1
> tmux send-keys -t a3c:ps 'CUDA_VISIBLE_DEVICES= /anaconda/envs/StarterAgent/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --visualise --job-name ps' Enter
> tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES= /anaconda/envs/StarterAgent/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --visualise --job-name worker --task 0 --remotes 1' Enter
> tmux send-keys -t a3c:w-1 'CUDA_VISIBLE_DEVICES= /anaconda/envs/StarterAgent/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --visualise --job-name worker --task 1 --remotes 1' Enter
> tmux send-keys -t a3c:tb 'tensorboard --logdir /tmp/pong --port 12345' Enter
> tmux send-keys -t a3c:htop htop Enter
> 
> no server running on /private/tmp/tmux-501/default
> Use tmux attach -t a3c to watch process output
> Use tmux kill-session -t a3c to kill the job
> Point your browser to http://localhost:12345 to see Tensorboard

Which seems to suggest it's working. However, trying to navigate to http://localhost:12345 results in a "localhost refused to connect" error in Chrome. Any suggestions?

**Comment by remoba** [comment]
Your output suggests the tmux session was created, you didn't post the actual output of the session. Use 'tmux attach -t a3c' to attach yourself to the tmux session, and then navigate to the tensorboard window

**Comment by Butsuri** [comment]
The tmux session was created and commands executed, but there could have been errors **after** the session has loaded. (usually a python import error, like tensorflow couldn't load for some reason)

Try 'tmux a' and scroll through the windows to see the output and if the expected commands are still loading.
