### ISSUE TITLE
Easiest way to have an agent playing with the most likely action (no exploration / learning)?

### ISSUE THREAD

**Issue by crci** [openai/universe-starter-agent#106]
As I put in the title, I was wondering if there is a simple way of having one of the agents just playing as best as possible (i.e. taking always the most likely action), with no exploration (and even no learning). This would be useful to check the real skill level that the agent has achieved so far.

Thanks!

**Comment by ethancaballero** [comment]
have separate test thread that takes argmax (instead of multinomial sample) of policy.
