### ISSUE TITLE
can't install opencv3. dead link?

### ISSUE THREAD

**Issue by jonatslim** [openai/universe-starter-agent#111]
when i execute this line....
`conda install -y -c https://conda.binstar.org/menpo opencv3`

i get this message

> Fetching package metadata ...ERROR requests.packages.urllib3.connection:_match_hostname(360): Certificate did not match expected hostname: conda.binstar.org. Certificate: {'subjectAltName': [('DNS', 'anaconda.com'), ('DNS', 'anacondacloud.com'), ('DNS', 'anacondacloud.org'), ('DNS', 'binstar.org'), ('DNS', 'wakari.io')], 'subject': ((('commonName', u'anaconda.com'),),)}
> 
> CondaHTTPError: HTTP None None for url <https://conda.binstar.org/menpo/osx-64/repodata.json>
> Elapsed: None
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> SSLError(SSLError(CertificateError("hostname 'conda.binstar.org' doesn't match either of 'anaconda.com', 'anacondacloud.com', 'anacondacloud.org', 'binstar.org', 'wakari.io'",),),)

is this a dead opencv3 link?

**Comment by jonatslim** [comment]
after tickering a bit... i was able to install opencv package, not opencv3 using this line..

`conda install -y -c https://anaconda.org/menpo opencv`

**Comment by AbstractMonkey** [comment]
Same thing happened to me. Thanks for the fix.

**Comment by miguelangarano** [comment]
Hi friends look you just use this:
conda install -c menpo opencv3 
the other command doesn't works anymore
