### ISSUE TITLE
deterministic policy or stochastic policy

### ISSUE THREAD

**Issue by zhixy** [openai/universe-starter-agent#115]
In this repo, [a deterministic policy](https://github.com/openai/universe-starter-agent/blob/master/a3c.py#L125) is used, however, in the A3C paper, it is a stochastic policy (hope that I don't misunderstand), any reason for that?

**Comment by sanjeevkumar42** [comment]
This is not deterministic as action is sampled from distribution returned by network.

**Comment by zhixy** [comment]
Yes, I just noticed that, and coming to close this issue...Anyway, thx!
