### ISSUE TITLE
 flashgames.NeonRace-v0 gets in weird state at times

### ISSUE THREAD

**Issue by EMCP** [openai/universe-starter-agent#121]
` flashgames.NeonRace-v0` seemed to have one agent die (window disappeared when I wasn't watching) , and the other window looks to be stuck in a strange state

anyone else seen this?

Is there a way to reload progress from my training if I restart?

![screenshot from 2017-09-09 10-11-33](https://user-images.githubusercontent.com/3691722/30238639-d9b86148-954a-11e7-8734-ef23c6678c48.png)

**Comment by dtcarls** [comment]
Not sure if you found an answer yet, but yes I have also run into this game state. To fix, you can kill your sessions "tmux kill-session" and run the train.py command again. If you use the same log directory the progress is continued; however, if you had 2 workers, 1 died and 1 was in this state it may have "learned" some bad behavior. Best to start from scratch.
