### ISSUE TITLE
Image problem

### ISSUE THREAD

**Issue by kane77** [openai/universe-starter-agent#122]
I have installed all dependencies and have been able to start, however when I look into tensorboard, the images there look strange. Not sure what it could be caused by.

![screen shot 2017-09-14 at 13 02 14](https://user-images.githubusercontent.com/19916/30426701-4834b7d8-994d-11e7-9114-3da206583409.png)

**Comment by TheCrazyT** [comment]
Got the same problem using ubuntu17 under virtualbox.

**Comment by TheCrazyT** [comment]
Solved it by pulling universe-repo and installed that throug pip3.
Then i run "rm -Rf /tmp/pong && python3 train.py -e PongDeterministic-v4" and it now shows correct black&white images.

**Comment by AdamStelmaszczyk** [comment]
This looks similar to the issue I'm seeing: https://github.com/openai/universe-starter-agent/issues/133

@kane77 I haven't seen any images in TensorBoard... Did your visualization in a window (env.render()) look wrong in the same way as mine? Have you fixed it?
