### ISSUE TITLE
No server running issue

### ISSUE THREAD

**Issue by MFaisalZaki** [openai/universe-starter-agent#124]
I have the following error when I try to execute the "python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong" it says "no server running on /private/tmp/tmux-501/default"

Terminal log:
(openAI) Mustafas-MacBook-Pro:universe-starter-agent mustafafaisal$ python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong
Executing the following commands:
mkdir -p /tmp/pong
echo /Users/mustafafaisal/anaconda/bin/python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong > /tmp/pong/cmd.sh
kill $( lsof -i:12345 -t ) > /dev/null 2>&1
kill $( lsof -i:12222-12224 -t ) > /dev/null 2>&1
tmux kill-session -t a3c
tmux new-session -s a3c -n ps -d bash
tmux new-window -t a3c -n w-0 bash
tmux new-window -t a3c -n w-1 bash
tmux new-window -t a3c -n tb bash
tmux new-window -t a3c -n htop bash
sleep 1
tmux send-keys -t a3c:ps 'CUDA_VISIBLE_DEVICES= /Users/mustafafaisal/anaconda/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --job-name ps' Enter
tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES= /Users/mustafafaisal/anaconda/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --job-name worker --task 0 --remotes 1' Enter
tmux send-keys -t a3c:w-1 'CUDA_VISIBLE_DEVICES= /Users/mustafafaisal/anaconda/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --job-name worker --task 1 --remotes 1' Enter
tmux send-keys -t a3c:tb 'tensorboard --logdir /tmp/pong --port 12345' Enter
tmux send-keys -t a3c:htop htop Enter

no server running on /private/tmp/tmux-501/default
Use `tmux attach -t a3c` to watch process output
Use `tmux kill-session -t a3c` to kill the job
Point your browser to http://localhost:12345 to see Tensorboard

**Comment by Gidongwii** [comment]
I think that message is shown because you haven't create a tmux session before.

**Comment by dtcarls** [comment]
Run the command again and it should be gone if it concerns you.

**Comment by kevinkicho** [comment]
I have the same issue. Could someone advise?
