### ISSUE TITLE
Questions !! when i am using ubuntu 16.04 (what is conda --create ?)

### ISSUE THREAD

**Issue by wonchul-kim** [openai/universe-starter-agent#129]
I am using ubuntu 16.04.

I haven't used conda.... 

if don't want to use conda and run this code, what should i do?
(I installed everything mentioned)

This is what I could not do:
conda create --name universe-starter-agent python=3.5
source activate universe-starter-agent

**Comment by dtcarls** [comment]
Instead of:
> conda create --name universe-starter-agent python=3.5
> source activate universe-starter-agent
> brew install tmux htop cmake golang libjpeg-turbo      # On Linux use sudo apt-get install -y tmux htop cmake golang libjpeg-dev
> pip install "gym[atari]"
> pip install universe
> pip install six
> pip install tensorflow
> conda install -y -c https://conda.binstar.org/menpo opencv3
> conda install -y numpy
> conda install -y scipy

You can run these commands instead:
```
brew install tmux htop cmake golang libjpeg-turbo      # On Linux use sudo apt-get install -y tmux htop cmake golang libjpeg-dev
pip3 install "gym[atari]"
pip3 install universe
pip3 install six
pip3 install tensorflow==0.12.1
pip3 install opencv-python
pip3 install numpy
pip3 install scipy

```

Can see my gist here: https://gist.github.com/dtcarls/03c23fca2fba804cfd4ac99ef4780a29 to see how I installed.
