### ISSUE TITLE
VNC into environment

### ISSUE THREAD

**Issue by html5cat** [openai/universe-starter-agent#20]
Could you add a quick note on how to VNC into simulated env on a Mac? Tried using TurboVNC but seems to fail to connect.
Thank you!

**Comment by wagonhelm** [comment]
What command did you use for turbovnc, I am trying to do the same on Linux.

**Comment by gdb** [comment]
You should be able to just connect to `localhost:15900` in your browser (assuming you're using Docker for Mac — if Docker Machine you'll need to do `${docker_ip}:15900`).

Alternatively, you can use your system viewer as `open vnc://localhost:5900` (or `open vnc://${docker_ip}:5900`) or connect TurboVNC to that ip/port.
