### ISSUE TITLE
Universe-starter-agent kills any pre-existing tmux sessions

### ISSUE THREAD

**Issue by joabim** [openai/universe-starter-agent#23]
**Reproduction:** 
start a new tmux session according to
```tmux new -s testing_daemon```
run
```python train.py --num-workers 8 --env-id Pong-v0 --log-dir /tmp/notimportant```
in separate shell from universe-starter-agent dir to see that the original ```testing_daemon``` session now is dead. We're currently using tmux for other projects and I noticed that they were dead post universe-starter-agent initialization

**Comment by wagonhelm** [comment]
Line [48](https://github.com/openai/universe-starter-agent/blob/master/train.py#L48) of train.py runs tmux kill-session. You can just comment / delete that.

**Comment by joabim** [comment]
Ah yes, thank you!
