### ISSUE TITLE
Helping to learn

### ISSUE THREAD

**Issue by MarioBross69** [openai/universe-starter-agent#26]
Hello
I'm in ubuntu 16.04 running correctly NeonRace-v0, the example that you show in universe-starter-agent
When I connect via vnc to NeonRace, I can drive the car with the keyboard keys
When i do this, I'm really helping in the learning process?
Or my actions with the keyboard are useless?

Thanks

**Comment by pa-sword** [comment]
It does affect, but does not contribute to the learning process. The learning process is affected because the agent sees the rewards for your actions, but the agent can only send one keypress at a time. Any additional keypresses will be unknown to the model.

**Comment by MarioBross69** [comment]
Ok, thanks
