### ISSUE TITLE
Attempting to use uninitialized value

### ISSUE THREAD

**Issue by hmate9** [openai/universe-starter-agent#31]
When I am trying to use more than 1 worker, the first worker starts fine but all the others have an error like this one:

```
Caused by op 'local/hidden_1/w/read', defined at:
  File "worker.py", line 122, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "worker.py", line 114, in main
    run(args, server)
  File "worker.py", line 23, in run
    trainer = A3C(env, args.task)
  File "/Users/matehegedus/Downloads/universe-starter-agent/a3c.py", line 181, in __init__
    self.local_network = pi = DensePolicy(env.observation_space.shape, env.action_space.n)
  File "/Users/matehegedus/Downloads/universe-starter-agent/model.py", line 53, in __init__
    x = linear(x, 32, "hidden_1", normalized_columns_initializer(0.01))
  File "/Users/matehegedus/Downloads/universe-starter-agent/model.py", line 37, in linear
    w = tf.get_variable(name + "/w", [x.get_shape()[1], size], initializer=initializer)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 370, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value local/hidden_1/w
         [[Node: local/hidden_1/w/read = Identity[T=DT_FLOAT, _class=["loc:@local/hidden_1/w"], _device="/job:worker/replica:0/task:1/cpu:0"](local/hidden_1/w)]]
```

**Comment by yaroslavvb** [comment]
Which version of TensorFlow are you using? I tried in TensorFlow 0.11 with various numbers of workers and can't reproduce this.

Also, can you see that your worker tmux prints ""Initializing all parameters."?
This is supposed by called by Supervisor and printed [here](https://github.com/openai/universe-starter-agent/blob/master/worker.py#L33)

As a temporary work-around, you could add `sess.run(tf.initialize_variables([v for v in tf.all_variables() if  v.name.startswith("local")])` right before ` trainer.start(sess, summary_writer)`.

**Comment by fgvbrt** [comment]
Hi, I had the same issue, some workers(not all) fail to initialize variables. TensorFlow version 0.12.0-rc0. Adding line that @yaroslavvb proposed fixed problem.

**Comment by MKorablyov** [comment]
I had a similar problem on 0.10, however, adding sess.run(tf.initialize_variables([v for v in tf.all_variables() if v.name.startswith("local")])). And initializing both local and global variables did not help. The code works with tf.train.batch with one thread, but fails on multiple threads. Exact output is below:

`Total memory: 7.93GiB
Free memory: 6.81GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:838] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980M, pci bus id: 0000:01:00.0)
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/read = Identity[T=DT_INT32, _class=["loc:@Variable_1"], _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1)]]
W tensorflow/core/framework/op_kernel.cc:940] Failed precondition: Attempting to use uninitialized value Variable_1`

**Comment by yaroslavvb** [comment]
There was a similar problem solved in https://github.com/openai/universe-starter-agent/issues/44, can you see if the solution helps?

In particular, in `worker.py`, replace the following line

    trainer.start(sess, summary_writer)

with

    sess.run(trainer.sync)
    trainer.start(sess, summary_writer)

**Comment by MKorablyov** [comment]
It was late at that time, so I wrote in a wrong repo. It should have been TF. I solved my issue by collecting all uninitialized variables into a list and initializing them. tf.global_variable_initializer() did not work for a yet unknown reason.

**Comment by yaroslavvb** [comment]
I guess because tf.global_variable_initializer() doesn't have local variables. You can do `sess.run([tf.global_variable_initializer(), tf.local_variables_initializer()])`

**Comment by MKorablyov** [comment]
That was the very first thing I've tried. The problem was related to tf.train.batch and delay in the main thread. What I think happened is that secondary threads could somehow requested variables before those were initialized.
