### ISSUE TITLE
cv2.resize() incredibly slow

### ISSUE THREAD

**Issue by thegyro** [openai/universe-starter-agent#33]
For processing the frames, I see that cv2.resize() is being used. I tried running the starter code in both a c4.4xlarge (8 workers) and m4.10xlarge (16 workers) instance. In both, I see my global_step/sec at around only 120. Instead of cv2.resize(), if I use scipy's resize I get much better performance (around 1000 steps/sec). From running `perf top`, I see a lot of time spent in communicating in the process libgomp.so. I tried setting  `OMP_NUM_THREADS=1`, but the problem seems to persist. Can someone please explain how to fix this?

**Comment by tlbtlbtlb** [comment]
Which scipy resize function are you using? Have you confirmed it produces very similar results? And what environment are you testing with?

`scipy.misc.imresize(... interp='nearest')` is fast, but because it just subsamples pixels it will miss features of the input that the agent would need to learn.

**Comment by thegyro** [comment]
@tlbtlbtlb  I am using the default interpolation option which is `bilinear`. Nevertheless cv2.resize() shouldn't be this slow right? Any idea why this is happening? 

I have attached the graph showing results I get running the starter code on a c4.4xlarge machine with 8 workers.  You can see that the global_step/sec is 120. That is really slow. 

![cv_resize](https://cloud.githubusercontent.com/assets/4838833/21276055/fc4dba16-c3cf-11e6-8eb7-f677d9b6be70.png)

**Comment by tlbtlbtlb** [comment]
The speed you get is puzzling. On my c4.2xlarge instance using the current universe-starter-agent and 8 workers I get over 500 steps/sec:

![image](https://cloud.githubusercontent.com/assets/219508/21277989/a5627f08-c38d-11e6-9fbf-ea2143bc6eb6.png)

Command:
```
python train.py --num-workers 8 --env-id PongDeterministic-v3 --log-dir /tmp/pong
```

pip info includes:
```
opencv-python (3.1.0.3)
mpi4py (2.0.0)
tensorflow (0.12.0rc1)
```

Bilinear when scaling down an image can entirely miss pixels. It depends on the game, but for something like asteroids

**Comment by thegyro** [comment]
Ah! I updated opencv to 3.1 from 2.4 and tensorflow from 0.11 to 0.12. It is working well now! Thanks!
