### ISSUE TITLE
Issue with Viewing VNC

### ISSUE THREAD

**Issue by nplevitt** [openai/universe-starter-agent#34]
I managed to view the `gym-core.PongDeterministic-v3` environment through VNC last night using `open vnc://localhost:5900`, but now when I try to run that command I get an error saying "You cannot control your own screen", using `Screen Sharing` as the default VNC app on OSX 10.12

I've tried to connect through both `TurboVNC` and `VNC Viewer`, and when I connect through `localhost:5900` it just connects to a copy of my desktop rather than to the Gym environment.

I'm running Docker locally and using Python 2.7. When I look at the tmux and Tensorboard output everything seems to be running fine, I just can't view through VNC.

**Comment by nplevitt** [comment]
Turns out this is an issue with Docker and persisting images. I will close here and open a different issue.

**Comment by kdbanman** [comment]
@nplevitt I have the exact same issue you're having, also with OSX 10.12 default VNC app.

What did you end up doing to solve it?

I don't think the Universe starter agent is using docker, because while the training is active I have nothing running via docker:

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
# ...
```

**Comment by tlbtlbtlb** [comment]
Some environments use Docker, some don't. The `gym-core.XXX` ones don't, they use an Atari emulator in the same process.

**Comment by kdbanman** [comment]
Oh interesting.  I'll try to find some docs on environments before asking further questions.

**Comment by gsastry** [comment]
I'm running into the same issue on OS X, any luck resolving this @kdbanman @nplevitt ?

**Comment by kdbanman** [comment]
My problem was that I was running with


--env-id PongDeterministic-v3


which doesn't expose a vnc endpoint. When I switched to this environment

--env-id gym-core.PongDeterministic-v3

the vnc client rendered just fine.

**Comment by kdbanman** [comment]
My problem was that I was running with

    --env-id PongDeterministic-v3


which doesn't expose a vnc endpoint. When I switched to this environment

    --env-id gym-core.PongDeterministic-v3

the vnc client rendered just fine.

**Comment by gsastry** [comment]
Hmm, I'm using that environment but I get the same error.

```
(universe-starter-agent) bash-4.4$ python train.py --num-workers 2 --env-id gym-core.PongDeterministic-v3 --log-dir /tmp/vncpong
Executing the following commands:
mkdir -p /tmp/vncpong
echo /Users/girish/anaconda/envs/universe-starter-agent/bin/python train.py --num-workers 2 --env-id gym-core.PongDeterministic-v3 --log-dir /tmp/vncpong > /tmp/vncpong/cmd.sh
tmux kill-session -t a3c
tmux new-session -s a3c -n ps -d bash
tmux new-window -t a3c -n w-0 bash
tmux new-window -t a3c -n w-1 bash
tmux new-window -t a3c -n tb bash
tmux new-window -t a3c -n htop bash
sleep 1
tmux send-keys -t a3c:ps 'CUDA_VISIBLE_DEVICES= /Users/girish/anaconda/envs/universe-starter-agent/bin/python worker.py --log-dir /tmp/vncpong --env-id gym-core.PongDeterministic-v3 --num-workers 2 --job-name ps' Enter
tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES= /Users/girish/anaconda/envs/universe-starter-agent/bin/python worker.py --log-dir /tmp/vncpong --env-id gym-core.PongDeterministic-v3 --num-workers 2 --job-name worker --task 0 --remotes 1' Enter
tmux send-keys -t a3c:w-1 'CUDA_VISIBLE_DEVICES= /Users/girish/anaconda/envs/universe-starter-agent/bin/python worker.py --log-dir /tmp/vncpong --env-id gym-core.PongDeterministic-v3 --num-workers 2 --job-name worker --task 1 --remotes 1' Enter
tmux send-keys -t a3c:tb 'tensorboard --logdir /tmp/vncpong --port 12345' Enter
tmux send-keys -t a3c:htop htop Enter

can't find session a3c
Use `tmux attach -t a3c` to watch process output
Use `tmux kill-session -t a3c` to kill the job
Point your browser to http://localhost:12345 to see Tensorboard
(universe-starter-agent) bash-4.4$ open vnc://localhost:5900
(universe-starter-agent) bash-4.4$```

I'm probably doing something wrong... any ideas?

**Comment by tlbtlbtlb** [comment]
@gsastry I don't see an error there. What does the VNC viewer show? What do you see in the various panes when you start tmux?

**Comment by gsastry** [comment]
It looks like this is the same issue that @nplevitt ran into here: https://github.com/openai/universe-starter-agent/issues/35

I can access VNC by incrementing the port. 

Thanks for the help :)

**Comment by a1noack** [comment]
@gsastry so you were simply able to view through vnc by executing:
open vnc://localhost:5901 
or 
open vnc://localhost:5902, 3, 4, etc.??

**Comment by gsastry** [comment]
Yeah, that's right.
