### ISSUE TITLE
Persisting Docker Images

### ISSUE THREAD

**Issue by nplevitt** [openai/universe-starter-agent#35]
I was having an issue with viewing my environments through VNC using `open vnc://localhost:5900` and have found that it is an issue with old Docker containers persisting. If you have multiple Docker containers stored locally the localhost port iteratively increases, i.e. 5901, 5902, 5903...

I've been using `tmux kill-session` to terminate my agents, but it looks like that does not terminate the local Docker images as well. Restarting Docker seems to clean out old containers, but the containers are still hosted starting at `localhost:5901` and up, not `localhost:5900`

**Comment by rafaljozefowicz** [comment]
You can add `docker rm $(docker ps -q)` into your train.py script, which should take care of the containers.

**Comment by tlbtlbtlb** [comment]
Fixed by https://github.com/openai/universe-starter-agent/commit/a670bdaba284bccb7b96d60a4d7a0d9dc231685b
