### ISSUE TITLE
ImportError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn_cell'

### ISSUE THREAD

**Issue by tlbtlbtlb** [openai/universe-starter-agent#43]
Using tensorflow 0.12.1:

Traceback (most recent call last):
  File "worker.py", line 8, in <module>
    from a3c import A3C
  File "/Users/tlb/openai/universe-starter-agent/a3c.py", line 5, in <module>
    from model import LSTMPolicy
  File "/Users/tlb/openai/universe-starter-agent/model.py", line 4, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn_cell import BasicLSTMCell
ImportError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn_cell'

@futurely What version of tensorflow did you find that this worked on?

**Comment by KaixiangLin** [comment]
got same error, it's not working in 0.11 either.

**Comment by futurely** [comment]
Nightly build of 0.12.1 on 2017-01-04. I should have tested with the stable release.
tensorflow_gpu-0.12.1-cp27-none-linux_x86_64.whl

**Comment by futurely** [comment]
There were quite a lot of "breaking Changes to the API" in the [release 0.12.0](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#breaking-changes-to-the-api-1) and [more recent version](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#breaking-changes-to-the-api).

**Comment by tlbtlbtlb** [comment]
Current version works on both tf 0.11 and tf 0.12
