### ISSUE TITLE
Playing game locally

### ISSUE THREAD

**Issue by alex84726** [openai/universe-starter-agent#55]
Excuse me,
    I've completed training a model of pong game(using command : python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong ). 
    How can I use the model checkpoint to see how it performed on the game visually?

**Comment by tlbtlbtlb** [comment]
`train.py` will have started a tensorboard server, which you can see by navigating to http://localhost:12345/ in a browser. If you've stopped the run, you can start a new tensorboard server with `tensorboard --logdir /tmp/pong --port 12345'

**Comment by alex84726** [comment]
Thanks @tlbtlbtlb 
How about using the model playing a game?  
( Like env.rendor() in gym )

**Comment by tlbtlbtlb** [comment]
You can start training again, and it will use the previous checkpoint. Then use a VNC client such as TurboVNC to connect to `localhost:5900`.

**Comment by nohe427** [comment]
I cannot connect locally to localhost:5900.  I cannot watch it train visually unless it is through tensorboard
