### ISSUE TITLE
unknown env spec tag

### ISSUE THREAD

**Issue by Dorozhko-Anton** [openai/universe-starter-agent#57]
I've got the error.
``` python
File ".../universe-starter-agent/a3c.py", line 142, in env_runner
    if terminal or length >= timestep_limit:
TypeError: unorderable types: int() >= NoneType()
```
It points to the code
``` python
timestep_limit = env.spec.tags.get('wrapper_config.TimeLimit.max_episode_steps')
if terminal or length >= timestep_limit:
```

But I was not able to find where that tag is loaded to specs. I was working with PongDetermenistic-v3 env.
flashgames.NeonRace-v0 - is working fine.

**Comment by yaroslavvb** [comment]
Are you using latest version of universe? There was a related bug in this part of the code released to universe last week,  can try `pip install --upgrade ...` and see if that helps?

**Comment by Dorozhko-Anton** [comment]
thx, problem solved
