### ISSUE TITLE
Error on python train.py

### ISSUE THREAD

**Issue by raineroviir** [openai/universe-starter-agent#58]
running command `python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong` in the universe-starter-agent conda env.
I get the following error:
python: can't open file 'train.py': [Errno 2] No such file or directory

**Comment by tlbtlbtlb** [comment]
You must be in wrong directory. You should be in directory where universe-starter-agent is checked out, which will include `train.py`.

**Comment by raineroviir** [comment]
I'm in the home directory ~.  I can't find the file train.py. Is it something that should be installed?

**Comment by tlbtlbtlb** [comment]
train.py is part of this (universe-starter-agent) repository. You download it with git:
```
$ cd ~
$ git clone https://github.com/openai/universe-starter-agent
$ cd universe-starter-agent
$ python train.py
```
