### ISSUE TITLE
The agent hit the global step limit, how do I restore from checkpoints and restore trainning

### ISSUE THREAD

**Issue by syhdog** [openai/universe-starter-agent#62]
I am working on a ideal that requires long time training, about 10 days. I forgot to modify the global step limit. So the agent stopped at 100M step. I want to restore the model and go on my training. I have been look through the code and wandered what should I do.

Sincerely thank you to open this project, it has been a very very respectable work and help a lot with my research. Truly, we find it really enjoyable to develop agents. Thank you a lot.

**Comment by KaixiangLin** [comment]
In `worker.py`, add those two lines to specify the variables you want to restore:
```python
    variables_to_restore = [v for v in tf.all_variables() if v.name.startswith("global")]
    pre_train_saver = FastSaver(variables_to_restore)
```
Add one more line in `init_fn`
```python
    def init_fn(ses):
        logger.info("Initializing all parameters.")
        ses.run(init_all_op)
        pre_train_saver.restore(ses,
                                "THE_PATH_TO_YOUR_MODEL/model.ckpt-4986751")

**Comment by syhdog** [comment]
Than you very much, it's be a great help.
