### ISSUE TITLE
ubuntu getting started

### ISSUE THREAD

**Issue by iHateInventNames** [openai/universe-starter-agent#65]
root@name-System-Product-Name:/home/name# pip install gym[atari]
Collecting gym[atari]
  Downloading gym-0.7.3.tar.gz (150kB)
    100% |████████████████████████████████| 153kB 1.6MB/s 
Requirement already satisfied: numpy>=1.10.4 in /usr/lib/python2.7/dist-packages (from gym[atari])
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from gym[atari])
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from gym[atari])
Collecting pyglet>=1.2.0 (from gym[atari])
  Downloading pyglet-1.2.4-py2-none-any.whl (964kB)
    100% |████████████████████████████████| 972kB 981kB/s 
Collecting atari_py>=0.0.17 (from gym[atari])
  Downloading atari-py-0.0.18.tar.gz (750kB)
    100% |████████████████████████████████| 757kB 1.2MB/s 
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from gym[atari])
Collecting PyOpenGL (from gym[atari])
  Downloading PyOpenGL-3.1.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 827kB/s 
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->gym[atari])
Installing collected packages: pyglet, atari-py, PyOpenGL, gym
  Running setup.py install for atari-py ... done
  Running setup.py install for PyOpenGL ... done
  Running setup.py install for gym ... done
Successfully installed PyOpenGL-3.1.0 atari-py-0.0.18 gym-0.7.3 pyglet-1.2.4
root@name-System-Product-Name:/home/name# pip install universe
Collecting universe
  Downloading universe-0.21.2.tar.gz (133kB)
    100% |████████████████████████████████| 143kB 1.1MB/s 
Requirement already satisfied: autobahn>=0.16.0 in /usr/local/lib/python2.7/dist-packages (from universe)
Requirement already satisfied: docker-py==1.10.3 in /usr/local/lib/python2.7/dist-packages (from universe)
Requirement already satisfied: docker-pycreds==0.2.1 in /usr/local/lib/python2.7/dist-packages (from universe)
Collecting fastzbarlight>=0.0.13 (from universe)
  Downloading fastzbarlight-0.0.14.tar.gz (728kB)
    100% |████████████████████████████████| 737kB 1.0MB/s 
Collecting go-vncdriver>=0.4.8 (from universe)
  Downloading go_vncdriver-0.4.19.tar.gz (638kB)
    100% |████████████████████████████████| 645kB 1.2MB/s 
Requirement already satisfied: gym>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from universe)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python2.7/dist-packages (from universe)
Collecting PyYAML>=3.12 (from universe)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 2.2MB/s 
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from universe)
Collecting twisted>=16.5.0 (from universe)
  Downloading Twisted-16.6.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 366kB/s 
Collecting ujson>=1.35 (from universe)
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 2.8MB/s 
Requirement already satisfied: txaio>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from autobahn>=0.16.0->universe)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: requests<2.11,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from go-vncdriver>=0.4.8->universe)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym>=0.7.0->universe)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow>=3.3.0->universe)
Requirement already satisfied: zope.interface>=3.6.0 in /usr/lib/python2.7/dist-packages (from twisted>=16.5.0->universe)
Collecting constantly>=15.1 (from twisted>=16.5.0->universe)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=16.5.0->universe)
  Downloading incremental-16.10.1-py2.py3-none-any.whl
Installing collected packages: fastzbarlight, go-vncdriver, PyYAML, constantly, incremental, twisted, ujson, universe
  Running setup.py install for fastzbarlight ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lWeysK/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pryYFZ-record/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
      warnings.warn(msg)
    running install
    running build
    error: [Errno 13] Permission denied
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lWeysK/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pryYFZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lWeysK/fastzbarlight/
root@name-System-Product-Name:/home/name# pip install six
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages
root@name-System-Product-Name:/home/name# pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-0.12.1-cp27-cp27mu-manylinux1_x86_64.whl (43.1MB)
    100% |████████████████████████████████| 43.1MB 27kB/s 
Collecting mock>=2.0.0 (from tensorflow)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 5.3MB/s 
Requirement already satisfied: numpy>=1.11.0 in /usr/lib/python2.7/dist-packages (from tensorflow)
Collecting protobuf>=3.1.0 (from tensorflow)
  Downloading protobuf-3.2.0-py2.py3-none-any.whl (360kB)
    100% |████████████████████████████████| 368kB 2.1MB/s 
Collecting wheel (from tensorflow)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 4.6MB/s 
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from tensorflow)
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock>=2.0.0->tensorflow)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages/setuptools-18.1-py2.7.egg (from protobuf>=3.1.0->tensorflow)
Installing collected packages: funcsigs, mock, protobuf, wheel, tensorflow
  Found existing installation: funcsigs 0.4
    Uninstalling funcsigs-0.4:
      Successfully uninstalled funcsigs-0.4
Successfully installed funcsigs-1.0.2 mock-2.0.0 protobuf-3.2.0 tensorflow-0.12.1 wheel-0.29.0
root@name-System-Product-Name:/home/name# conda install -y -c https://conda.binstar.org/menpo opencv3
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 9, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/usr/local/lib/python2.7/dist-packages/conda/base/context.py", line 18, in <module>
    from ..common.configuration import (Configuration, MapParameter, PrimitiveParameter,
  File "/usr/local/lib/python2.7/dist-packages/conda/common/configuration.py", line 40, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
root@name-System-Product-Name:/home/name# conda install -y numpy
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 9, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/usr/local/lib/python2.7/dist-packages/conda/base/context.py", line 18, in <module>
    from ..common.configuration import (Configuration, MapParameter, PrimitiveParameter,
  File "/usr/local/lib/python2.7/dist-packages/conda/common/configuration.py", line 40, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
root@name-System-Product-Name:/home/name# conda install -y scipy
Traceback (most recent call last):
  File "/usr/local/bin/conda", line 9, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 558, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2682, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/usr/local/lib/python2.7/dist-packages/conda/base/context.py", line 18, in <module>
    from ..common.configuration import (Configuration, MapParameter, PrimitiveParameter,
  File "/usr/local/lib/python2.7/dist-packages/conda/common/configuration.py", line 40, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named ruamel.yaml.comments
root@name-System-Product-Name:/home/name#

**Comment by iHateInventNames** [comment]
next problem:

getting started step `pip install universe`:


$ **sudo su**
root@name-System-Product-Name:/home/name/source/universe# pip install universe
Collecting universe
  Using cached universe-0.21.2.tar.gz
Requirement already satisfied: autobahn>=0.16.0 in /usr/local/lib/python2.7/dist-packages (from universe)
Requirement already satisfied: docker-py==1.10.3 in /usr/local/lib/python2.7/dist-packages (from universe)
Requirement already satisfied: docker-pycreds==0.2.1 in /usr/local/lib/python2.7/dist-packages (from universe)
Collecting fastzbarlight>=0.0.13 (from universe)
  Using cached fastzbarlight-0.0.14.tar.gz
Collecting go-vncdriver>=0.4.8 (from universe)
  Using cached go_vncdriver-0.4.19.tar.gz
Requirement already satisfied: gym>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from universe)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python2.7/dist-packages (from universe)
Collecting PyYAML>=3.12 (from universe)
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from universe)
Collecting twisted>=16.5.0 (from universe)
  Using cached Twisted-16.6.0.tar.bz2
Collecting ujson>=1.35 (from universe)
  Using cached ujson-1.35.tar.gz
Requirement already satisfied: txaio>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from autobahn>=0.16.0->universe)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: requests<2.11,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/lib/python2.7/dist-packages (from docker-py==1.10.3->universe)
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from go-vncdriver>=0.4.8->universe)
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym>=0.7.0->universe)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow>=3.3.0->universe)
Requirement already satisfied: zope.interface>=3.6.0 in /usr/lib/python2.7/dist-packages (from twisted>=16.5.0->universe)
Collecting constantly>=15.1 (from twisted>=16.5.0->universe)
  Using cached constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=16.5.0->universe)
  Using cached incremental-16.10.1-py2.py3-none-any.whl
Building wheels for collected packages: universe, fastzbarlight, go-vncdriver, PyYAML, twisted, ujson
  Running setup.py bdist_wheel for universe ... done
  Stored in directory: /root/.cache/pip/wheels/6c/57/18/28d35aa4651eef7606a5334022d2109ec310b1b0a2ff231500
  Running setup.py bdist_wheel for fastzbarlight ... error
  Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nTsIqv/fastzbarlight/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpLbST7Vpip-wheel- --python-tag cp27:
  /usr/lib/python2.7/distutils/extension.py:133: UserWarning: Unknown Extension options: 'optional'
    warnings.warn(msg)
  running bdist_wheel
  running build
  error: [Errno 13] **Permission denied**
  
  ----------------------------------------
  Failed building wheel for fastzbarlight
  Running setup.py clean for fastzbarlight
  Running setup.py bdist_wheel for go-vncdriver ... -

**Comment by iHateInventNames** [comment]
**/home/name/source/universe# make**
rm -rf dist
python setup.py sdist
running sdist
running egg_info
writing requirements to universe.egg-info/requires.txt
writing universe.egg-info/PKG-INFO
writing top-level names to universe.egg-info/top_level.txt
writing dependency_links to universe.egg-info/dependency_links.txt
reading manifest file 'universe.egg-info/SOURCES.txt'
writing manifest file 'universe.egg-info/SOURCES.txt'
running check
creating universe-0.21.2
creating universe-0.21.2/universe
creating universe-0.21.2/universe.egg-info
creating universe-0.21.2/universe/envs
creating universe-0.21.2/universe/envs/tests
creating universe-0.21.2/universe/envs/vnc_core_env
creating universe-0.21.2/universe/kube
creating universe-0.21.2/universe/pyprofile
creating universe-0.21.2/universe/remotes
creating universe-0.21.2/universe/remotes/compose
creating universe-0.21.2/universe/rewarder
creating universe-0.21.2/universe/runtimes
creating universe-0.21.2/universe/scoreboard
creating universe-0.21.2/universe/spaces
creating universe-0.21.2/universe/utils
creating universe-0.21.2/universe/vectorized
creating universe-0.21.2/universe/vncdriver
creating universe-0.21.2/universe/vncdriver/screen
creating universe-0.21.2/universe/vncdriver/vendor
creating universe-0.21.2/universe/wrappers
creating universe-0.21.2/universe/wrappers/experimental
making hard links in universe-0.21.2...
hard linking README.rst -> universe-0.21.2
hard linking setup.py -> universe-0.21.2
hard linking universe/__init__.py -> universe-0.21.2/universe
hard linking universe/configuration.py -> universe-0.21.2/universe
hard linking universe/error.py -> universe-0.21.2/universe
hard linking universe/runtimes.yml -> universe-0.21.2/universe
hard linking universe/twisty.py -> universe-0.21.2/universe
hard linking universe.egg-info/PKG-INFO -> universe-0.21.2/universe.egg-info
hard linking universe.egg-info/SOURCES.txt -> universe-0.21.2/universe.egg-info
hard linking universe.egg-info/dependency_links.txt -> universe-0.21.2/universe.egg-info
hard linking universe.egg-info/requires.txt -> universe-0.21.2/universe.egg-info
hard linking universe.egg-info/top_level.txt -> universe-0.21.2/universe.egg-info
hard linking universe/envs/__init__.py -> universe-0.21.2/universe/envs
hard linking universe/envs/diagnostics.py -> universe-0.21.2/universe/envs
hard linking universe/envs/dummy_vnc_env.py -> universe-0.21.2/universe/envs
hard linking universe/envs/vnc_env.py -> universe-0.21.2/universe/envs
hard linking universe/envs/vnc_flashgames.py -> universe-0.21.2/universe/envs
hard linking universe/envs/vnc_gtav.py -> universe-0.21.2/universe/envs
hard linking universe/envs/vnc_internet.py -> universe-0.21.2/universe/envs
hard linking universe/envs/vnc_starcraft.py -> universe-0.21.2/universe/envs
hard linking universe/envs/vnc_wog.py -> universe-0.21.2/universe/envs
hard linking universe/envs/tests/__init__.py -> universe-0.21.2/universe/envs/tests
hard linking universe/envs/tests/test_semantics.py -> universe-0.21.2/universe/envs/tests
hard linking universe/envs/vnc_core_env/__init__.py -> universe-0.21.2/universe/envs/vnc_core_env
hard linking universe/envs/vnc_core_env/key.py -> universe-0.21.2/universe/envs/vnc_core_env
hard linking universe/envs/vnc_core_env/translator.py -> universe-0.21.2/universe/envs/vnc_core_env
hard linking universe/envs/vnc_core_env/vnc_core_env.py -> universe-0.21.2/universe/envs/vnc_core_env
hard linking universe/kube/__init__.py -> universe-0.21.2/universe/kube
hard linking universe/kube/discovery.py -> universe-0.21.2/universe/kube
hard linking universe/pyprofile/__init__.py -> universe-0.21.2/universe/pyprofile
hard linking universe/remotes/__init__.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/allocator_remote.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/build.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/docker_remote.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/hardcoded_addresses.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/healthcheck.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/remote.py -> universe-0.21.2/universe/remotes
hard linking universe/remotes/compose/__init__.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/remotes/compose/colors.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/remotes/compose/container.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/remotes/compose/log_printer.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/remotes/compose/progress_stream.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/remotes/compose/signals.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/remotes/compose/utils.py -> universe-0.21.2/universe/remotes/compose
hard linking universe/rewarder/__init__.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/connection_timer.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/env_status.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/merge.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/remote.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/reward_buffer.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/reward_proxy_server.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/rewarder_client.py -> universe-0.21.2/universe/rewarder
hard linking universe/rewarder/rewarder_session.py -> universe-0.21.2/universe/rewarder
hard linking universe/runtimes/__init__.py -> universe-0.21.2/universe/runtimes
hard linking universe/runtimes/registration.py -> universe-0.21.2/universe/runtimes
hard linking universe/scoreboard/__init__.py -> universe-0.21.2/universe/scoreboard
hard linking universe/spaces/__init__.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/diagnostics.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/hardcoded.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/joystick_action_space.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/joystick_event.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/vnc_action_space.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/vnc_event.py -> universe-0.21.2/universe/spaces
hard linking universe/spaces/vnc_observation_space.py -> universe-0.21.2/universe/spaces
hard linking universe/utils/__init__.py -> universe-0.21.2/universe/utils
hard linking universe/utils/display.py -> universe-0.21.2/universe/utils
hard linking universe/vectorized/__init__.py -> universe-0.21.2/universe/vectorized
hard linking universe/vectorized/core.py -> universe-0.21.2/universe/vectorized
hard linking universe/vectorized/multiprocessing_env.py -> universe-0.21.2/universe/vectorized
hard linking universe/vectorized/vectorize_filter.py -> universe-0.21.2/universe/vectorized
hard linking universe/vncdriver/__init__.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/auth.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/constants.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/dual_proxy_server.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/error.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/fbs_reader.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/fbs_writer.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/libvnc_session.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/server_messages.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/vnc_client.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/vnc_proxy_server.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/vnc_session.py -> universe-0.21.2/universe/vncdriver
hard linking universe/vncdriver/screen/__init__.py -> universe-0.21.2/universe/vncdriver/screen
hard linking universe/vncdriver/screen/base.py -> universe-0.21.2/universe/vncdriver/screen
hard linking universe/vncdriver/screen/numpy_screen.py -> universe-0.21.2/universe/vncdriver/screen
hard linking universe/vncdriver/screen/pyglet_screen.py -> universe-0.21.2/universe/vncdriver/screen
hard linking universe/vncdriver/screen/screen_buffer.py -> universe-0.21.2/universe/vncdriver/screen
hard linking universe/vncdriver/vendor/__init__.py -> universe-0.21.2/universe/vncdriver/vendor
hard linking universe/vncdriver/vendor/pydes.py -> universe-0.21.2/universe/vncdriver/vendor
hard linking universe/wrappers/__init__.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/action_space.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/blocking_reset.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/diagnostics.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/gym_core.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/gym_core_sync.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/joint.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/logger.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/monitoring.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/multiprocessing_env.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/recording.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/render.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/throttle.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/time_limit.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/timer.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/vectorize.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/vision.py -> universe-0.21.2/universe/wrappers
hard linking universe/wrappers/experimental/__init__.py -> universe-0.21.2/universe/wrappers/experimental
hard linking universe/wrappers/experimental/action_space.py -> universe-0.21.2/universe/wrappers/experimental
hard linking universe/wrappers/experimental/observation.py -> universe-0.21.2/universe/wrappers/experimental
Writing universe-0.21.2/setup.cfg
creating dist
Creating tar archive
removing 'universe-0.21.2' (and everything under it)
twine upload dist/*
/bin/sh: 1: **twine: not found**
Makefile:2: ошибка выполнения рецепта для цели «upload»
make: *** [upload] Ошибка 127
root@name-System-Product-Name:/home/name/source/universe# sudo **apt-get install twine**

**Comment by iHateInventNames** [comment]
Looks like impossible to use Universe w/o hacking on Universe

**Comment by tlbtlbtlb** [comment]
`make` is not the way to install universe. Please read the instructions at https://github.com/openai/universe#install-universe

**Comment by iHateInventNames** [comment]
alright, do not bother with such a little thing as unability to set the project up
