### ISSUE TITLE
tf.VERSION: object has no attribute 'VERSION'

### ISSUE THREAD

**Issue by dvcanton** [openai/universe-starter-agent#66]
Just a simple issue:

> File "a3c.py", line 10
        use_tf12_api = distutils.version.LooseVersion(tf.VERSION) >= distutils.version.LooseVersion('0.12.0')
     AttributeError: 'module' object has no attribute 'VERSION'

`tf.__version__` works though. I am still using the 0.10.0 version

**Comment by dvcanton** [comment]
File "a3c.py", line 10, in <module>
        use_tf12_api = distutils.version.LooseVersion(tf.VERSION) >= distutils.version.LooseVersion('0.12.0')
    AttributeError: 'module' object has no attribute 'VERSION'

**Comment by tlbtlbtlb** [comment]
Only tensorflow 0.11 and up are supported.
