### ISSUE TITLE
Weights from `normalized_columns_initializer` are held constant

### ISSUE THREAD

**Issue by Joshua-Chin** [openai/universe-starter-agent#71]
`normalized_columns_initializer` returns a `tf.constant` instead of a `tf.Variable`. This means that the weights of the linear layers will be held constant through training. I'm not sure if this was intentional.

**Comment by tlbtlbtlb** [comment]
The tf.Variable is created in the `linear` function here: https://github.com/openai/universe-starter-agent/blob/master/model.py#L37. It is modified by the trainer to maximize reward. It is normal for the initializer of a variable to be a constant.
