### ISSUE TITLE
Performance on other Atari games

### ISSUE THREAD

**Issue by pengsun** [openai/universe-starter-agent#72]
Hi, Pong is a good sanity check. Has anyone tried/adopted the code (A3C-LSTM) on other Atari games like BreakoutDeterministic-v3 and SpaceInvadersDeterministic-v3, and managed to get average scores 500+ and 2500+ respectively?

I understand there is much difference with the A3C paper (like reward clipping, shared rms optimization, network architecture, input image size...) in this implementation... But I still can't reproduce the results on breakout and space_invaders after modifying the code... 

Any suggestion/discussion is welcomed!

**Comment by dgriff777** [comment]
I implemented an A3C-LSTM on those games and yes my model far exceeded those scores. SpaceInvadersDeterministic-v3 scores go as high 50,000 and average around 15,000. Saved trained models in my repo https://github.com/dgriff777/rl_a3c_pytorch
