### ISSUE TITLE
Continuous action space

### ISSUE THREAD

**Issue by favetelinguis** [openai/universe-starter-agent#79]
Would it be possible to also make a continuous action space version of A3C available. I find it not trivial to make the adjustments described in the original paper and would love to see how its done.

**Comment by bzier** [comment]
Same here. This is also related to issue #75. I would like to see an example of how to use anything other than the discrete action space that is currently used.

**Comment by michaelschaarschmidt** [comment]
What you need to do is implement something like a diagonal Gaussian policy, so you need to provide methods to sample and compute log-likelihoods from a Gaussian for updates.

Example here:
https://github.com/reinforceio/tensorforce/blob/master/tensorforce/models/distributed_pg_model.py#L101

**Comment by marekyggdrasil** [comment]
@michaelschaarschmidt unfortunately the link leads to 404, probably this repo is no longer public. Just like @bzier and @favetelinguis I'm also trying to adapt this agent to take decisions on different space than discrete as my problem does not map to discrete space. Could you provide more details?

**Comment by michaelschaarschmidt** [comment]
https://github.com/reinforceio/tensorforce is still public, the models have just moved.

**Comment by bzier** [comment]
@marekyggdrasil I haven't been back to this in months, so unfortunately, I can't really help with this. I never looked at this any more in depth to figure it out for my use-case. However, the repository mentioned in @michaelschaarschmidt's comment is still there, but the file was removed/renamed at some point. Here's a link to a previous commit version of the file (from around the date of Michael's comment):
https://github.com/reinforceio/tensorforce/blob/44fb7be090f2a08f10f3611d1872d7c09fc67032/tensorforce/models/distributed_pg_model.py#L101
