### ISSUE TITLE
tmux config renames windows

### ISSUE THREAD

**Issue by matttrent** [openai/universe-starter-agent#8]
The training script was failing with with `tmux can't find pane XXX` for each of the window names the script was trying to create.

After looking around, it seems that the default config on OS X (I didn't have a `.tmux.conf` in my home directory) is to rename the windows to be that of the path the script was run from.

The following setting added to `.tmux.conf` disables the behavior and the script can run as expected:

    set-option -g allow-rename off

**Comment by 0bserver07** [comment]
In case you didn't find tmux defualt file, the file can be located at `~/.tmux.conf` or created.

**Comment by Banginpadr** [comment]
i cant find tmux.conf. im using osx 10.9
