### ISSUE TITLE
flashgames NeonRace  does not launch

### ISSUE THREAD

**Issue by yangcheng** [openai/universe-starter-agent#84]
I was able to run the Atari agent pong, and the dustdrive agent following [(https://github.com/openai/universe)]

but the following cmd to launch NeonRace does not work
python train.py --num-workers 2 --env-id flashgames.NeonRace-v0 --log-dir /tmp/neonrace

Any suggestions?

**Comment by NickLands** [comment]
I am not sure if my problem is the same as the OP, but I am getting an error which causes NeonRace to not launch either.

FileNotFoundError: [Errno 2] No such file or directory: '/home/nick/.conda/envs/universe-starter-agent/lib/python3.5/site-packages/universe/runtimes/flashgames.json'

**Comment by crci** [comment]
@NickLands Install universe from the repo https://github.com/openai/universe/issues/171

**Comment by NickLands** [comment]
@crci Solved.Thanks
