### ISSUE TITLE
Readme missing golang dependency

### ISSUE THREAD

**Issue by NHDaly** [openai/universe-starter-agent#88]
Saw build error when building `go-vncdriver`.
Something like "no directory 'go'".

**Comment by NHDaly** [comment]
Also missing libjpeg-turbo, which i added in #90

**Comment by tlbtlbtlb** [comment]
These dependencies are documented in the go-vncdriver project, at https://github.com/openai/go-vncdriver

**Comment by NHDaly** [comment]
Sorry for my late response.

> These dependencies are documented in the go-vncdriver project

Sure, that's true, but `vncdriver` isn't listed as a dependency either, so there's no way for a beginner to know to look there. :)

My understanding is that this repo exists to enable beginners to get started training models in the OpenAi universe as easily as possible. There are many great researchers and enthusiastic learners who aren't familiar developing in unix environments and installing software. This is not the interesting part about reinforcement learning!

Shouldn't we make on-boarding as simple as possible? The first step to doing that is making sure the instructions describe *all* the required steps to set up the model! Also, I've already done the work of listing the dependencies in the above PRs. 😃

**Comment by NHDaly** [comment]
@gcullie:
+Greg Cullen who organized a meetup to introduce people to OpenAi, and was where we saw some of these build issues.

**Comment by NHDaly** [comment]
:) Thanks!!
