### ISSUE TITLE
Tmux not keeping virtual environments active

### ISSUE THREAD

**Issue by ScottJordan** [openai/universe-starter-agent#9]
When train.py is called and generates the tmux sessions. The virtual environment is not carried over into the tmux sessions. 

I installed everything in an anaconda python 3 environment and it failed because it didn't keep the environment active. Afte installing everything in the main conda environment and it worked. I was quickly looking around for a way to set tmux to automatically keep it active, but haven't found away.  If anyone else has solved it, it would be good to see a solution. I'll post one if I figure it out.

**Comment by joabim** [comment]
One solution is to prepend 'source activate your_conda_environment &&' to base_cmd in create_tmux_commands following

```
def create_tmux_commands(session, num_workers, remotes, env_id, logdir):
    # for launching the TF workers and for launching tensorboard
    base_cmd = ['source activate tensorflow &&',
        'CUDA_VISIBLE_DEVICES=', sys.executable, 'worker.py',
        '--log-dir', logdir, '--env-id', env_id,
        '--num-workers', str(num_workers)]
```
where tensorflow is my tf conda env

**Comment by yaroslavvb** [comment]
It seems 4.2.0 version of anaconda is not compatible with parallel environment, so downgrade to 4.0.10 is needed https://github.com/conda/conda/issues/2837
