### ISSUE TITLE
should model.py line 52 be tf.nn.relu instead of tf.nn.elu?

### ISSUE THREAD

**Issue by harrypann** [openai/universe-starter-agent#97]
As titled. I think this line should be  x = tf.nn.relu(conv2d(x, 32, "l{}".format(i + 1), [3, 3], [2, 2]))
instead of  x = tf.nn.elu(conv2d(x, 32, "l{}".format(i + 1), [3, 3], [2, 2]))

**Comment by tlbtlbtlb** [comment]
For the games we tested on, `elu` got slightly higher scores than `relu`. But universe-starter-agent is intended as a starting point, a framework for experimentation, so you should experiment with that and other modifications to see what gets the best results.
