### ISSUE TITLE
Failed building wheel for atari-py (zlib is missing)

### ISSUE THREAD

**Issue by Hyperparticle** [openai/universe-starter-agent#98]
I encountered an error when trying to follow the README on Ubuntu 17.04. It worked up until the following command.
```
pip install "gym[atari]"
```
Which results in the error:
```
fatal error: zlib.h: No such file or directory
```

I fixed this by doing
```
sudo apt-get install libz-dev
```

Should the README be updated to include this package? I don't know if anyone else had this problem, but I'm documenting it here.

**Comment by blakecc** [comment]
I had quite a bit of trouble with zlib. The thing that finally worked for me:

`sudo yum install zlib-devel.x86_64`
